---
title: "Discussion_4"
author: "Vanessa Rathbone"
date: "1/26/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(janitor)
library(tsibble)
library(feasts)
```

```{r}
truckee <- read_csv("truckee_river.csv", skip = 29) %>% 
  slice(-1) %>% 
  select(datetime, discharge_cfc) %>% 
  mutate(date = lubridate::mdy(datetime), 
         discharge_cfs = as.numeric(discharge_cfs))

#make it into a tsibble
truckee_ts <- truckee %>% 
  as_tsibble(key = NULL, index = date)

truckee_ts %>% 
  gg_season(discharge_cfc)

ggplot(data = truckee_ts, aes(x = date, y = discharge_cfs)) +
  geom_line()

```


```{r, echo = FALSE}
#now add interactive piece to the graphs
inputPanel(
  dateRangeInput(inputId = "dates",
                 label = "Select data range:", 
                 min = "2010-01-01",
                 max = "2021-01-24",
                 start = "2010-01-01", 
                 end = "2021-01-24",
                 format = "yyyy-mm-dd")
)

#create a reactive dataframe, use indexing to take elements from a vector for the widget to interact with

truckee_react <- reactive({
  
  truckee_ts %>% 
    filter(date >= input$dates[1],
           date <= input$dates[2])
  
})

#create a reactive graph

renderPlot({
  
  ggplot(data = truckee_react(), aes(x = date, y = discharge_cfs))
})



```


